client/src/App/pages/Mood.js, db/seeds/1 users.js, db/seeds/2 moods.js, index.js
Hello everyone,
We just seeded our tables:
* Users
* Moods
Please check this amazing code and let me know if there is any changes to be done
Byyye
=> Seed tables users and moods

client/package-lock.json, client/src/App/pages/Mood.js, client/src/App/pages/heatmap.css, client/src/App/pages/heatmap.js, db/seeds/2 moods.js, index.js
Hello Beautiful Team Members,
We've implemented a few thing:
* Backend check for input of the user
* If the input already exists, then updates it
* If the input doesnt exist, then adds it
* Heatmap rendering the info from DB
=> user input update/create mood implemented

client/src/App/pages/Mood.js, client/src/App/pages/heatmap.js, index.js
Hi everyone,
Note the following:
- heatmap now renders without refresh
- submit/save buttons have been removed due to auto re-rendering
Thanks,
Shivangna
=> render heatmap without refresh

db/seeds/3 journal.js
Take a look and be amazed with this wonderful seed
=> :tada: Seed for journal entries

client/src/App/App.js, client/src/App/pages/TodoList.js
Hey guys,
The add task to ToDo list is complete!
=> New tasks show on ToDo modal

client/package-lock.json, client/package.json, client/src/App/pages/Journal.js, client/src/App/pages/wordgraph.js
Hi everyone,
I created a component that renders the graph but does not yet connect to the database.
Regards,
Your fav team mate.
=> create a journal graph component that currently does not connect to db

client/src/App/pages/Journal.js, index.js
=> show the journal entry as an alert, does not yet post on DB

client/package-lock.json, client/public/index.html, client/src/App/App.js, client/src/App/pages/Mood.js, client/src/App/pages/TodoList.js, db/seeds/todo_tasks.js, index.js
render backend tasks to the front end
=> render backend tasks to front end

client/src/App/pages/Journal.js, index.js
the journal entries now store in the database. you can insert a new entry for a non-existing date or update the journal entry if it already exists
=> post journal entries to database

client/src/App/App.css, client/src/App/pages/Challenges.js
Hello greatest team ever,
Now, our Daily challenges save a state for each completed task.
Next implementation is:
- Graph to show percentage complete
- Reset the states at midnight
(PS: I will accept the PR myself...sorry :D )
=> Implemented on click for each challenge

client/package-lock.json, client/package.json, client/src/App/pages/Challenges.js
Hello Beautiful Team,
On part 3 of my solo adventure I implemented:
* Graph rendering based on the amount of challenges completed
Please check it out
=> Daily challenges p3

client/src/App/App.js, client/src/App/pages/TodoList.js, index.js
we can now add and delete tasks
=> Tododeltask2

client/src/App/pages/Navbarr.js, client/src/App/pages/TodoList.js, temp.txt
clears input field  ... sometimes
=> clears input field  ... sometimes

client/src/App.test.js, client/src/App/App.js, client/src/App/pages/Journal.js, client/src/App/pages/Mood.js, client/src/App/pages/Navbarr.js, client/src/App/pages/TodoList.js, client/src/App/pages/final-wordgraph.js, client/src/App/pages/gauge.js, client/src/index.js, index.js
Hello Everyone,
This merge shouldn't affect anything but warning we were having.
Thanks
=> Fix warning p1

db/seeds/3 journal.js
Hello Everyone,
I've updated the seed file "3 journal.js" and now it includes emotion for every input
Please take a look
=> Seed for Emotion

client/src/App/pages/Journal.js, db/seeds/3 journal.js
Hello Team,
Bug fix on the date change and possibly on the re-render of the liquid graphs
=> Bug Fix date update

client/package-lock.json, knexfile.js, package-lock.json
Hello Team,
I made some changes on knexfile.js to be able to use everything outside VAGRANT
Please
=> Out of Vagrant mission complete

client/src/App/App.js, client/src/App/pages/Api.js, client/src/App/pages/Journal.js
Hello Team,
MIkias helped us fix the date formats and the liquid gauge rendering.
Please check the code for conflicts
=> Bug fix on Liquid Gauge and Date formats

client/src/App/pages/final-wordgraph.js, index.js
Hello Team,
We fixed this stuff!! Yay
=> Buf Fix word graph rendering same data twice

client/src/App/pages/Journal.js, client/src/App/pages/gauge.js
Hello everyone,
Now, each liquid gauge has it's own color to reflect the mood
=> color change on liquid title

client/src/App/App.css, client/src/App/pages/TodoList.js
Hello Team,
I have made some changes on the ToDo List
* Drag and Drop function added
* Function completeHandler: still a work in progress -> the idea is to show a supportive message for each time the user completes a task
* Check Icon changed
* Trash Icon added
* Effects added:
- Drag and Drop: drag and dragging mouse pointer
- Hove over Check and Trash icons
Please let me know your opinions on it.
=> Implemented: drag and drop and extras

client/src/App/App.js, client/src/App/pages/TodoList.js, client/src/App/pages/completeMessages.js
Hello team,
I just implemented a function that display 1 out of 20 different messages when a user completes a task in To Do module
=> Message for Task Complete

client/src/App/App.css, client/src/App/pages/ChallengesMessages.js, client/src/App/pages/Mood.js, client/src/App/pages/heatmap.css, db/seeds/2 moods.js
Hello Team,
Everything is working fine with journal and module
=> Debuggin s seed
